### ISSUE TITLE
How to install a custom stack in your own Cloud Foundry cluster

### ISSUE THREAD

**Issue by jtwaleson** [cloudfoundry/cflinuxfs2#20]
Currently we ship the Java Runtime and various dependencies in the droplet but found the packaging, uploading to the blob store, downloading and unpacking steps to be quite slow (> 1 minute).

As we only have apps in our cluster which have common dependencies (Oracle Java Runtime, large .jars), it would be great if we can build our custom stack and install it on our CF cluster, so we can optimize the buildpack to omit certain things from the droplet as they are already present on the root fs.

Can this be done? Compiling our own stack was easy, but we have no clue on how to install it in CF.

**Comment by jtarchie** [comment]
@jtwaleson, great question.

Stacks are not easily updatable in a bosh deployment. There is no way to do a `cf create-stack`. The reasoning is that Cloud Foundry provides security updates to that stacks that we support.

We also compile the binaries in all the buildpacks against our stack. We can not guarantee that the binaries will work against another stack.

You would have to create you own dev release of Cloud Foundry to support stacks. I can get into more detail, but wanted to give you the reasoning why we don't recommend it.

**Comment by jtwaleson** [comment]
@jtarchie thanks for the quick reply. It makes sense. As an alternative, is there any way to access buildpack resources from the running container? If so we could pre-package the static resources in the buildpack and access them from both the bin/compile and droplet execution phases.

**Comment by jtarchie** [comment]
The buildpack resources would have to package with the app with the droplet is created. If you're using the Java buildpack, they could better answer this question, but I believe they have mechanisms for this exact purpose.

**Comment by jtwaleson** [comment]
Thanks, we already do exactly that. The problem is that the droplet gets pretty bloated and transferring that is slow. We're aiming to minimize time from app push to accepting http requests.

**Comment by jtarchie** [comment]
@jtwaleson highly recommend [blue-green](https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/blue-green.html) deployment to minimize such time. This is a release strategy for _near_ zero downtime deployments.

**Comment by jtwaleson** [comment]
Some more context: this is for our users' development environments, so it's mostly about getting changed code live as quickly as possible. Downtime is not an issue.

Your suggestions are great, it's just that we have a rather strange use case ;)

**Comment by djvdorp** [comment]
> You would have to create you own dev release of Cloud Foundry to support stacks. I can get into more detail, but wanted to give you the reasoning why we don't recommend it.
> @jtarchie, Oct 29, 2015, 1:57 PM GMT+1

I would actually be interested in some more detailed knowledge of creating your own dev release of Cloud Foundry, if you could give some info / pointers in the right direction that'd be great?
(Thanks for your time and effort on this by the way!)

**Comment by jtarchie** [comment]
@djvdorp the best thing I can point you to is our [CI script](https://github.com/cloudfoundry/buildpacks-ci/blob/master/scripts/stacks/upload-to-cf-release) that updates cf-release with the latest stack. We upload directly to the cf-release blob store. You'll have to setup BOSH with your own blob store to support it, which, to be honest, I have no idea how to do. :frowning: 

If you have any more questions, please start it on the [cf-dev mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/) as others might have production experience with making their own stacks. If you do, please link back to it here, so others may find the thread.

**Comment by emalm** [comment]
Hi, @jtwaleson (and @jtarchie),

You may also be interested in how [diego-release](https://github.com/cloudfoundry-incubator/diego-release) supplies the cflinuxfs2 stack to the Diego cells via its [rootfses job template](https://github.com/cloudfoundry-incubator/diego-release/tree/develop/jobs/rootfses). I think you could theoretically do something similar for your stack as follows:
- colocate another job on Diego Cells to provide your own rootfs,
- associate that rootfs with a stack name in the config for Diego's rep component,
- change some configuration in Diego's stager and nsync components to register the new stack for use in staging tasks and app instances,
- configure CC to know about the new stack.

For those last ones, if you look in cf-release and diego-release for the string `cflinuxfs2`, you should find the appropriate places to register your stack similarly.

Thanks,
Eric, CF Runtime Diego PM

**Comment by djvdorp** [comment]
> If you have any more questions, please start it on the cf-dev mailing list as others might have production experience with making their own stacks. If you do, please link back to it here, so others may find the thread.
> @jtarchie, Oct 30, 2015, 1:35 PM GMT+1

Thanks for the suggestion, I have done exactly that and it can be found here:
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/2SGIBGXTP6XJVURJ4RZIAYRAR33BAZN4/
