### ISSUE TITLE
Upgrade curl beyond 7.35 to avoid regression

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/cflinuxfs2#21]
7.35 introduced a regression ( see https://github.com/guzzle/RingPHP/issues/26)

Can we upgrade to 7.36 or above?

**Comment by jtarchie** [comment]
@johnmcteague, we use the latest patched packages from Canonical (Ubuntu creator). For the trusty distro, they've version locked it to 7.35.0. We only receive the security patches for 7.35.0.

Are you experiencing the issue with `curl` and RingPHP?

**Comment by johnmcteague** [comment]
Its actually curl under the hood of https://github.com/onoi/http-request that causes the issue (I gave the RingPhp reference as an example).

We run SemanticMediaWiki (https://semantic-mediawiki.org) on CF using the PHP buildpack. SMW uses onoi/http-request lib.

**Comment by flavorjones** [comment]
@johnmcteague Thanks for asking this question.

Unfortunately, as @jtarchie points out, the rootfs is derived from Canonical's Ubuntu 14.04 (trusty) distribution, which ships curl 7.35.

It's currently not our policy to cherry-pick individual packages, and we're unlikely to change that policy unless there are compelling security issues involved.

Can you help us understand the severity of this problem? How is it affecting you? Are there any known workarounds?

**Comment by johnmcteague** [comment]
We verified a workaround on Friday that involves downgrading http to 1.0 via a curl option. For now that will suffice. This issue has helped clarify our understanding of the LTS position of the rootfs, so its been benefical. 

Out of curiosity when 16.04 LTS is released in April, is it proposed rootfs would move with it at some point? LTS for Ubuntu is technically 5 years and 12.04 was skipped for rootfs.

**Comment by flavorjones** [comment]
We haven't started discussions of supporting 16.04 yet. There are some related issues I'd like to work on before we start supporting two Linux stacks in earnest.
