### ISSUE TITLE
stack upload problem

### ISSUE THREAD

**Issue by mike00151** [cloudfoundry/cflinuxfs2#26]
Hello all

I follow the instruction to build a custom cloudfoundry stack successfully.

How can I upload my custom stack to an existing cloudfoundry environment?

**Comment by jtarchie** [comment]
@mike00151, thanks for the question.

We don't have specific instructions to upload custom stacks. There was an [issue](https://github.com/cloudfoundry/stacks/issues/20) opened and it was discussed why we don't recommend this. We can not guarantee that a user will have consistent experience with our stack and buildpacks.

Why did you build your own stack?

**Comment by mike00151** [comment]
@jtarchie , thanks for the replying.

My goal is to install a reverse proxy on each cloud foundry warden container for modifying out going http/https request.

I expect all the warden container will contain a installed reverse proxy.

I saw there is document for creating a stack (http://apidocs.cloudfoundry.org/215/)

I can execute create stack API (POST /v2/stacks) but can not find upload stack API.

**Comment by flavorjones** [comment]
@mike00151 Again, installing a custom stack is not a supported operation on CF, but if you don't care, you should be able to make it work by modifying your cf-release bosh manifest.

We're not cf-release experts, so if you run into challenges, I'd recommend taking this question to the cf-dev@ mailing list.

Good luck!
