### ISSUE TITLE
Can we have libgmp-dev in cflinuxfs please?

### ISSUE THREAD

**Issue by totherme** [cloudfoundry/cflinuxfs2#32]
As discussed in the [cloudfoundry slack](https://cloudfoundry.slack.com/archives/buildpacks/p1465151734000012) I'm trying to write a haskell buildpack ([this](https://github.com/BrianMMcClain/heroku-buildpack-haskell) one doesn't seem to work anymore) and believe I need libgmp-dev. Could it be included in cflinuxfs please?

Thanks!

**Comment by geramirez** [comment]
This is something that we'd be happy to add and we'll have a new patch sometime this week.

**Comment by Dannyzen** [comment]
@totherme We've included libgmp-dev in https://github.com/cloudfoundry/stacks/commit/49ec0e93c4402f1e8af346c8c4bde015cd079668#diff-13932739e093b80a4eb23dc3d245cb34R218. It should be available in an upcoming version of cf-release

**Comment by totherme** [comment]
Awesome, thanks!
