### ISSUE TITLE
GraphViz Support?

### ISSUE THREAD

**Issue by geramirez** [cloudfoundry/cflinuxfs2#33]
We've received a [request](https://github.com/cloudfoundry/python-buildpack/pull/41#issuecomment-223097886) to add GraphViz support to rootfs. 

If this is something that you're looking for please let us know. 
## 

Buildpacks team

**Comment by Dannyzen** [comment]
Due to lack of interest expressed by the community we've opted to not put graphviz into the stacks. If you'd like to use graphviz please feel free to vendor it in your application.
