### ISSUE TITLE
RFC: Removing Ruby 2.2.4 and adding Ruby 2.3.1 in cflinuxfs2

### ISSUE THREAD

**Issue by sclevine** [cloudfoundry/cflinuxfs2#36]
Hi All,

The cflinuxfs2 stack currently includes Ruby 2.2.4. The official CF buildpacks have standardized on Ruby 2.3.1, and we would like to avoid bumping the Ruby version by two minor versions when Ruby 2.4 is released. We propose that we upgrade Ruby 2.2.4 to Ruby 2.3.1 in cflinuxfs2.

Note that the cflinuxfs2 stack has historically contained Ruby, even though the [Ruby Buildpack](https://github.com/cloudfoundry/ruby-buildpack) provides separate Ruby binaries. This change would not affect the Ruby versions provided by the Ruby buildpack.

Our preference is to make this change to cflinuxfs2 by 9/16/2016. If you have any concerns or feedback, please comment on this issue.

**Comment by flavorjones** [comment]
+1 to upgrading the rootfs ruby regularly.

**Comment by sclevine** [comment]
Released in [1.82.0](https://github.com/cloudfoundry/stacks/releases/tag/1.82.0).
