### ISSUE TITLE
non-unicode font support 

### ISSUE THREAD

**Issue by David-VMware** [cloudfoundry/cflinuxfs2#46]
Hi Team,

Do we support non-unicode font in our ubuntu rootfs container base image?

An java app generates an BMP image which contains some Chinese characters. The image looks good when run in local computer, for example macbook. However the Chinese characters won’t be generated when run this app in PCF.

I have set `JAVA_OPTS '-Duser.language=zh_TW -Duser.country=TW'` however the Chinese character won't display properly. 

Run in mackbook
`DavidZhou:Downloads dzhou$ java -jar image.jar 
BMP file generated: /Users/dzhou/D53.bmp
^C
DavidZhou:Downloads dzhou$`

Run in PCF
`ubuntu@bosh-stemcell:~$ cf push image-test -p image.jar -b java_buildpack_offline -f manifest.yml`
`ubuntu@bosh-stemcell:~$ cf set-env image-test JAVA_OPTS '-Duser.language=zh_TW -Duser.country=TW'`
`ubuntu@bosh-stemcell:~$ cf restage image-test`

Generated image file in Mac
![d53_mac](https://user-images.githubusercontent.com/17395452/35670581-e7f3ceaa-0773-11e8-9625-d5d8ff1322d9.jpg)

Generated image file in PCF
![d53_20180125](https://user-images.githubusercontent.com/17395452/35670580-e7c40cc4-0773-11e8-9d35-dc5e53212b82.jpg)

**Comment by David-VMware** [comment]
Hi Team,

Any advice is welcome!

**Comment by dgodd** [comment]
Hi @David-Pivotal I suspect you should actually be talking to the java buildpacks team. I have linked @nebhale  on this ticket to discuss

**Comment by sclevine** [comment]
@dgodd chatting with @nebhale, we think Java is using a font rendering library in cflinuxfs2. Could you prioritize something to investigate?

Maybe we're deleting the necessary fonts [here](https://github.com/cloudfoundry/cflinuxfs2/blob/master/cflinuxfs2/build/install-packages.sh#L125)? (Maybe not -- we seem to have some fonts in `/usr/share/fonts`.)

Or maybe we don't include localized fonts? If so, how big are they?

**Comment by David-VMware** [comment]
@dgodd Is it possible for customer to add a Custom Stack by following [Adding a Custom Stack](https://docs.cloudfoundry.org/running/custom-stack.html)? 
If yes, could you advise the procedure I shall follow to add the localized fonts, folder `/usr/share/fonts`?

@sclevine Thank you for your comments!

**Comment by sclevine** [comment]
In general, PCF customers should not use custom stacks. Doing so is not supported, blocks critical security patches that apply to apps, and in some cases can result in existing apps failing to launch.

Until we determine if we need to add additional fonts to cflinuxfs2, I would recommend pushing the additional fonts with the app and configuring the app or buildpack to use those fonts. For example, it might be possible to use a `.profile` script in the app directory to copy the fonts from the app directory into `/home/vcap/.local/share/fonts/` at launch.

**Comment by dgodd** [comment]
@sclevine @David-Pivotal The problem with adding fonts is determining which ones to add, there will never be one which supports every language out there. As an example for size Stephen I found ttf-wqy-zenhei which is 10Mb and supports chinese (although it is probably not the best option just the first I found)

As an app developer I have never relied on system fonts (even when I was also managing the system), I have always packaged fonts with my app and personally feel that is the only safe plan as a developer. Packaging the font also means you can control which one is on the system. The alternative as I see it is using apt-buildpack to install

**Comment by nebhale** [comment]
I'm leaning in this direction as well.  Part of running in a container is that you should be more or less self-contained (once you take into account buildpack contributions).  I think fonts come under this same situation where the application should embed a font and explicitly register it for usage rather than expect it to be around.  In fact, I'll bet that in the Java application, you'll find an API for registered fonts so you don't need to do anything with `.profile` or `.local/share/fonts/`.  That's the path that I'd explore next.

**Comment by nebhale** [comment]
I don't think that either the rootfs or the buildpack needs to change for this, but why don't we close this issue out in lieu of cloudfoundry/java-buildpack#548 to unify discussion into a single issue.  That seems to be a more appropriate location to explore Java-application-level solutions to this issue.

**Comment by dgodd** [comment]
I agree @nebhale
