### ISSUE TITLE
Consider installing gss-ntlmssp package by default

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cflinuxfs2#49]
This package is commonly needed by .NET core applications to consume Kerberos authenticated services.  Any chance of getting this package installed by default in the rootfs?

**Comment by sclevine** [comment]
There doesn't appear to be a trusty package for it:
https://packages.ubuntu.com/search?keywords=gss-ntlmssp

We will add it to cflinuxfs3 today though -- we happen to be finalizing the package list right now :)

**Comment by youngm** [comment]
@sclevine cflinuxfs3 would be great.  Thanks!

**Comment by youngm** [comment]
Actually @sclevine after doing some more digging adding the gss-ntlmssp package might not be the home run I thought it would be for .NET Core and NTLM.  Perhaps you should leave it out of cflinuxfs3 until I'm more sure it will actually provide the value I think it will?  Any issues with adding this package to cflinuxfs3 after the package list is finalized?  What do you think?

**Comment by astrieanna** [comment]
This has been added to cflinuxfs3. (both `gss-ntlmssp-dev` and `gss-ntlmssp`)
